baseURL                 = "https://sandeep-yadav.com.np"
languageCode            = "en"
title                   = "Sandeep Kumar Yadav"
enableRobotsTXT         = true
disableKinds            = ["taxonomy", "term"]

[params]
author      = "Sandeep Kumar Yadav"
email       = "079bel078.sandeep@pcampus.edu.np"
github      = "https://github.com/sandeep-yadav-71b955274"
linkedin    = "https://linkedin.com/in/sandeep-yadav-71b955274"
phone       = "+977-980-844-0772"
location    = "Pulchowk, Lalitpur, Nepal"
accent      = "#60a5fa"   # sky-400